name: Notes Application CI Pipeline
# create a CI pipeline based on the assignment specification
# remember to commit often

on:
  branches:
    - "**"

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd src
        npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
    - name: Run e2e Tests
      run: |
        cd src
        npm run start &
        npm run test:e2e
